### PR TITLE
Adding a first example as a cookbook entry of using ADEV for correctly differentiating probabilistic programs

### PR DESCRIPTION
**Pull request by MathieuHuot**

### CODE REVIEW

**Comment by MathieuHuot** [comment]
@sritchie I think this doesn't need a detailed review, and can easily be merged. It's just a simple first cookbook to show some interaction between GenJAX and differentiation.

**Comment by sritchie** [comment]
Sounds good, fix the build errors and let's merge!

**Review by sritchie — APPROVED** [review]

**Comment by MathieuHuot** [comment]
@sritchie I don't understand the remaining linter bug for ruff. Locally it's not complaining. Is it possible my local ruff busted or something? I thought it'd be updated automatically with poetry but maybe not>

**Comment by MathieuHuot** [comment]
> @sritchie I don't understand the remaining linter bug for ruff. Locally it's not complaining. Is it possible my local ruff busted or something? I thought it'd be updated automatically with poetry but maybe not>

ok nevermind it was indeed the ruff version on my end which was not up to date.

**Pull request merged**
