### PR TITLE
update adev_example with latest code from adev_demo

### PR DESCRIPTION
**Pull request by mhuebert**

### CODE REVIEW

**Review by sritchie — APPROVED** [review]
approve, just one ruff error, looks like!

**Comment by mhuebert** [comment]
@sritchie try as I might, I cannot get this ruff check to pass. I first formatted the imports using vscode, then ran ruff --fix locally and committed the changes. Are there special settings being applied somehow?

**Comment by sritchie** [comment]
I bet the pre commit hook and the GitHub action are out of sync, I will try and fix and merge when it works

**Comment by mhuebert** [comment]
@sritchie thanks!

**Pull request merged**
