### PR TITLE
Fixes and tests for MaskingCombinator

### PR DESCRIPTION
**Pull request by jburnim**

### CODE REVIEW

**Comment by jburnim** [comment]
cc @midfield

**Comment by femtomc** [comment]
Thanks for filling these in! Hopefully this helps thinking on https://github.com/probcomp/dcolmap/pull/250.

**Comment by femtomc** [comment]
@jburnim Will review this tomorrow, thanks for the patience.

**Review by femtomc — APPROVED** [review]
This LGTM, following our discussion today.

**Comment by jburnim** [comment]
Thanks!

**Pull request merged**
